console.log("Welcome!!");
console.log('<-- Default log with an emoji');
console.print('Default print. No emoji');
console.set({size: "2em", useTable: true});
console.party("Party", "Time");
console.crystal("Crystal", "looks", "awesome");
console.burn("BY", "FIRE", "BE", "PURGED");
console.static("Static theme");
console.color("cooolooors");
console.spring("Is Spring Awesome??", true);
console.rand("That's so random");
console.print("Printing", "all", "the things", 123, false);
console.set({style: "pencil"});
console.print("Pencil Theme (Default)");
console.set({style: "pink"});
console.print("Beautiful Pink Theme");
console.set({style: "gold"});
console.print("Sexy Gold Theme");
console.set({style: "fancy", color: "#fff"});
console.print("Fancy Pants Theme");
console.set({style: "fancy"});
console.print("Fancy Pants Theme");
console.set({style: "rainbow"});
console.print("Happy Rainbow Theme");
console.set({style: "threeD"});
console.print("3D Theme");
console.set({style: "neon"});
console.print("Favorite Neon Theme");
console.set({style: "code"});
console.print("Code Theme");
